[workspace]
resolver = "2"
members = ["crates/oci-builder", "crates/oci-runner"]

[workspace.package]
version = "0.1.7"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.85"
repository = "https://github.com/geoffsee/oci-lib"
homepage = "https://github.com/geoffsee/oci-lib"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
