[package]
name = "oci-runner"
version.workspace = true
description = "CLI for running a rootfs with embedded libcontainer"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "oci-runner"
path = "src/main.rs"

[dependencies]
libcontainer-ffi.workspace = true
clap = { version = "4", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
ror-proto.workspace = true
libc = "0.2"
